### ISSUE TITLE
Error When Sending Message Using Node Libaries

### ISSUE THREAD

**Issue by dmoreland** [Azure/azure-iot-sdks#191]
I get the following exception when sending messages using the Node.JS library, The issue happens intermittently. 

> Unhandled rejection TypeError: Cannot read property 'on' of undefined
>     at C:\Source\Messenger\app.js:156:17
>     at Amqp.<anonymous> (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\lib\amqp.js:157:17)
>     at C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\lib\amqp.js:54:19
>     at C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\lib\amqp.js:84:17
>     at tryCatcher (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\util.js:11:23)
>     at Promise._settlePromiseFromHandler (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\promise.js:489:31)
>     at Promise._settlePromise (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\promise.js:546:18)
>     at Promise._settlePromise0 (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\promise.js:591:10)
>     at Promise._settlePromises (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\promise.js:670:18)
>     at Async._drainQueue (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\async.js:129:16)
>     at Async._drainQueues (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\async.js:139:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (C:\Source\Messenger\node_modules\azure-iot-device\node_modules\azure-iot-common\node_modules\amqp10\node_modules\bluebird\js\release\async.js:16:14)

**Comment by damonbarry** [comment]
@dmoreland, what version of the azure-iot-device package are you using? Or if you're using the code directly from the GitHub repo, what's the head commit ID?

**Comment by dmoreland** [comment]
im using the NPM package version 1.0.0-preview.9

**Comment by pierreca** [comment]
Hi @dmoreland I'm going to look more closely into it... sorry for the delay. there have been a couple of SDK updates since. I was wondering if you tried again and if it changed anything.

Also can you describe what you mean by "intermittently"? I'd like to get a repro on my end but I don't know how often you see this and how your code works to create that problem... do you have a consistent way to reproduce the bug?

**Comment by dmoreland** [comment]
I havent seen the issue in a while so it may of been resolved with one of
the recent changes.

**Comment by tameraw** [comment]
@dmoreland - Thanks for the update. We'll go ahead and close this issue and if still having problems, please update us.
