### ISSUE TITLE
Azure IOT Java SDK Android

### ISSUE THREAD

**Issue by XavierGe** [Azure/azure-iot-sdks#647]
I haven’t been able to successfully use all the features of the Azure IOT Java SDK on an Android device:

1)Client part of the SDK:
-The gradle compile `'com.microsoft.azure.iothub-java-client:iothub-java-device-client:1.0.2'`  doesn’t work because it’s a Java 8 lib.
-So I have rebuild the library from the SDK source with Java 7 via Maven.
-I can successfully run my project with this lib, can send and receive messages on the IOT Hub, but only with MQTT and HTTPS.
-But the project cannot work with AMQPS, I get an SSL issue:
`06-21 10:34:33.462 9573-9598/com.lpg.azuretestclient W/SslEngineFacadeFactory: unable to load org.bouncycastle.openssl.PEMReader
06-21 10:34:33.462 9573-9598/com.lpg.azuretestclient W/SslEngineFacadeFactory: unable to load org.bouncycastle.openssl.PasswordFinder
06-21 10:34:33.462 9573-9598/com.lpg.azuretestclient W/SslEngineFacadeFactory: unable to load bouncycastle provider`

2)Service part of the SDK
-The gradle `compile 'com.microsoft.azure.iothub-java-client:iothub-java-service-client:1.0.2'` doesn’t work because it’s a Java 8 lib.
-But I cannot rebuild the lib in Java 7, this part requires the Java 8 jdk

**Comment by olivierbloch** [comment]
Hi @XavierGe 
This has been addressed in more recent releases of the Java SDK and Maven package (i think around 1.0.6). Can you please try again with the latest version?
Thanks

**Comment by XavierGe** [comment]
Hi Olivier,
 I have rebuild the Java SDKs ( Device 1.0.8, Service 1.0.7) with Maven 3.3.9 and still have the same issues.
Thanks,

**Comment by WksKing** [comment]
Hi All,
I encountered  the same problem, I want to use iot-hub maven library on Android platform, follow the tutorial at [https://azure.microsoft.com/zh-cn/documentation/articles/iot-hub-java-java-getstarted/](https://azure.microsoft.com/zh-cn/documentation/articles/iot-hub-java-java-getstarted/), simulated-device project is worked fine on Android platform, but both create-device-identity and read-d2c-messages depends on Java8 library, I can't access the public API of Java8. my build.gradle is:

**# create-device-identity:**
android {
    compileSdkVersion 24
    buildToolsVersion '24.0.1'

    defaultConfig {
        applicationId "com.wistron.demo.tool.create_device_identity"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        jackOptions{
            enabled true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/MSFTSIG.SF'
        exclude 'META-INF/MSFTSIG.RSA'
        exclude 'META-INF/BCKEY.SF'
    }

    dexOptions {
        incremental true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.microsoft.azure.iothub-java-client:iothub-java-service-client:1.0.7'
    compile 'com.android.support:appcompat-v7:24.1.1'
}

**# read-d2c-messages**
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"
    defaultConfig {
        applicationId "com.wistron.demo.tool.read_d2c_messages"
        minSdkVersion 24
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        jackOptions {
            enabled true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha1'
    testCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support:support-annotations:24.1.1'
    compile 'com.microsoft.azure:azure-eventhubs:0.7.5'
}

**appreciate your help.**

**Comment by anhashia** [comment]
Referencing #814 which covers same scenario

**Comment by anhashia** [comment]
Hi @XavierGe 
Please following instruction at https://github.com/Azure/azure-iot-sdks/blob/master/doc/iotcertification/iot_certification_android_java/iot_certification_android_java.md. 

Android **sample** is located at  java\device\samples\android-sample and by default uses 1.0.7 **iothub-java-device-client** library. AMQPS protocol should also work with this sample.

**Comment by anhashia** [comment]
Closing. Please re-activate if you have any further questions on this. Thanks !
