### ISSUE TITLE
nodejs AMQP sendEvent is not failing when connection is not available

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdks#852]
I am writing a device code using Node v1.0.15.

I want to implement a retry logic on sendEvent failure. However when I am calling sendEvent after disconnecting the computer from internet, it does not call _**callback**_. _I am disconnecting the cable after it successfully opens the connection_

```
client.sendEvent(msg, (err, res) => {
                if (err) {
                    logger.error(`Send Error`, err.message);
                } else {
                    logger.info(`Send Success`);
                }
            });
```

**Comment by pierreca** [comment]
hi @bmrpatel 

What OS are you using?

The `amqp10` library in our SDK is currently configured to call the callback only when the message gets settled, which cannot happen when disconnected. I have to look at why the messages being flagged as pending don't get their callback failed when the connection get disconnected though. Maybe @mbroadst and @noodlefrenzy can help?

On Windows, the `disconnect` event on the client should fire though, and a combination of `disconnect` being fired and not receiving the `MessageEnqueued` result should help you figure out which messages were sent and which were not. We've seen issues on Linux though (which is why I'm asking about the OS).

Just so you know, I'm about to dig a lot deeper into the retry logic (or lack thereof) of this part of the code, so if you'd like to describe in more details what you're trying to achieve (the type of retry policy/options you'd like to see, etc) it'll likely help me shape the SDK.

**Comment by mbroadst** [comment]
hey guys, could you give this commit a try: https://github.com/noodlefrenzy/node-amqp10/commit/98bd73498549cc48eb6ee64588b0cd7febee7cea. I think it should resolve your issue.

**Comment by pierreca** [comment]
@mbroadst thanks for the quick turn-around!
I did a quick test and the behavior is still the same, I don't see the promise returned by `send` ever get rejected after we get disconnected. It's very possible that the problem lies in how we call the `amqp10` library though (here: https://github.com/Azure/azure-iot-sdks/blob/master/node/common/transport/amqp/lib/amqp.js#L160)

I do get the `connection:closed` event, but the `send` operations themselves still don't fail.

**Comment by mbroadst** [comment]
you should verify if you are following this path: https://github.com/Azure/azure-iot-sdks/blob/master/node/common/transport/amqp/lib/amqp.js#L179. The code I pushed this morning indeed reject's the promise if a forceDetach occurs (this is what happens on shutdown with left-over open links), so first make sure you are seeing that behavior as well before tracking down the culprit in your code - I might have missed a use case

**Comment by bmrpatel** [comment]
Thanks @pierreca, I am using Linux (Ubuntu). 

@mbroadst I tried to replace this file directly into my node_modules folder and did some testing. Result is still the same as before.
 
Here is what I am doing:
- Start the application while it is connected to network _(initialize client, subscribe to `disconnect` event and send test message)_
- after sometime disconnect the network.
- wait for 10 mins to see if the `disconnect` event is emitted. _(not emitted)_
- try `sendEvent` and see if it errors out. (it does not error out, however after about 7 minutes it emits **multiple** `disconnect` event.)

**Another issue (perhaps linux only):** Multiple `disconnect` event triggered. Should I create new issue? I am only adding listener once. I have logging around this so I can see if it was called again. It is internally adding the same event listener multiple times and if I keep the program running for long times, I see error `warning: possible EventEmitter memory leak detected. 11 listeners added`.

**Comment by pierreca** [comment]
@bmrpatel regarding your last comment on the `EventEmitter` leak: could it be that you are creating the client with a `ConnectionString` rather than a `SharedAccessSignature` ? what you describe sounds a lot like a bug we're currently investigating.

**Comment by bmrpatel** [comment]
@pierreca Yes, I am using the `ConnectionString` to create the `Client`. Can you reference that bug here? Thanks

**Comment by pierreca** [comment]
Bug is not a GitHub issue, it's something we came up with internally. I'll update this issue with a reference to the commit when the fix gets checked in.

**Comment by pierreca** [comment]
The EventEmitter leak was fixed with 15f79123337cf135d2ec6bb097b65e04e155db04
Still investigating the callback not being called.

**Comment by bmrpatel** [comment]
Great, when will this be released? Or should I checkout develop branch and manually copy files to my node_modules? Thanks

**Comment by pierreca** [comment]
@bmrpatel We are releasing new packages in the next couple of days. Still working with @mbroadst on the original problem though, which is not getting a callback with an error when the message can't be sent.

**Comment by tameraw** [comment]
This has been fixed in the AMQP 1.0 library and we will update our SDK to use the new version for the next release (ETA 11/14)

**Comment by pierreca** [comment]
Should be fixed with the newly released packages. I'm closing this but feel free to reopen if you still see the issue.
